Repository ros2/examples, pull requests merged in 2019-03, with the labels that each got.

#222 rclpy action examples
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/__init__.py
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client.py
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_cancel.py
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_not_composable.py
  rclpy/actions/minimal_action_client/package.xml
  rclpy/actions/minimal_action_client/resource/examples_rclpy_minimal_action_client
  rclpy/actions/minimal_action_client/setup.cfg
  rclpy/actions/minimal_action_client/setup.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/__init__.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_defer.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_not_composable.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_queue_goals.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_single_goal.py
  rclpy/actions/minimal_action_server/package.xml
  rclpy/actions/minimal_action_server/resource/examples_rclpy_minimal_action_server
  rclpy/actions/minimal_action_server/setup.cfg
  rclpy/actions/minimal_action_server/setup.py
Labels: in review

#229 Backport Python Action examples to Crystal
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/__init__.py
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client.py
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_cancel.py
  rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_not_composable.py
  rclpy/actions/minimal_action_client/package.xml
  rclpy/actions/minimal_action_client/resource/examples_rclpy_minimal_action_client
  rclpy/actions/minimal_action_client/setup.cfg
  rclpy/actions/minimal_action_client/setup.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/__init__.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_defer.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_not_composable.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_queue_goals.py
  rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_single_goal.py
  rclpy/actions/minimal_action_server/package.xml
  rclpy/actions/minimal_action_server/resource/examples_rclpy_minimal_action_server
  rclpy/actions/minimal_action_server/setup.cfg
  rclpy/actions/minimal_action_server/setup.py
Labels: in progress

#227 update to use separated action types
  rclcpp/minimal_action_client/not_composable.cpp
  rclcpp/minimal_action_client/not_composable_with_cancel.cpp
  rclcpp/minimal_action_client/not_composable_with_feedback.cpp
  rclcpp/minimal_action_server/not_composable.cpp
Labels: enhancement, in review
